/**
 * Pre-render TikZ diagrams to SVG at build time.
 * 
 * Scans all markdown posts for ```tikz code blocks, compiles them via
 * node-tikzjax (a headless TeX->SVG pipeline), and writes a JSON manifest
 * mapping content hashes to SVG strings.
 * 
 * This eliminates the need for the browser to load a 5MB+ WASM TeX engine.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'fs';
import { resolve, dirname, relative } from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';
import pkg from 'node-tikzjax';
const tex2svg = pkg.default;

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');

const POSTS_DIR = resolve(ROOT, 'src/content/posts');
const OUTPUT_FILE = resolve(ROOT, 'src/generated/tikz-cache.json');
const POST_METADATA_FILE = resolve(ROOT, 'src/generated/post-metadata.ts');

function parseFrontmatter(rawMarkdown, id) {
  const frontmatterRegex = /^---\r?\n([\s\S]+?)\r?\n---\r?\n([\s\S]*)$/;
  const match = frontmatterRegex.exec(rawMarkdown);
  const defaultMeta = {
    id,
    title: 'Untitled',
    author: '',
    date: '',
    excerpt: '',
  };

  if (!match) {
    return defaultMeta;
  }

  const meta = { ...defaultMeta };

  for (const line of match[1].split('\n')) {
    const splitIndex = line.indexOf(':');
    if (splitIndex === -1) continue;

    const key = line.slice(0, splitIndex).trim();
    const value = line.slice(splitIndex + 1).trim().replace(/^['"]|['"]$/g, '');

    switch (key) {
      case 'title':
      case 'titleAr':
      case 'author':
      case 'date':
      case 'excerpt':
      case 'excerptAr':
      case 'audioEn':
      case 'audioAr':
      case 'transcriptEn':
      case 'transcriptAr':
      case 'thumbnail':
        meta[key] = value;
        break;
      case 'pinned':
        meta.pinned = ['true', 'yes', '1'].includes(value.toLowerCase());
        break;
      case 'pinnedRank': {
        const parsedRank = Number(value);
        if (Number.isFinite(parsedRank)) {
          meta.pinnedRank = parsedRank;
        }
        break;
      }
      case 'tags':
        meta.tags = value.split(',').map(tag => tag.trim()).filter(Boolean);
        break;
      default:
        break;
    }
  }

  return meta;
}

function toPosixPath(path) {
  return path.replace(/\\/g, '/');
}

function readMarkdownFiles(directory, baseDirectory = directory) {
  const files = [];

  for (const entry of readdirSync(directory)) {
    const fullPath = resolve(directory, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...readMarkdownFiles(fullPath, baseDirectory));
      continue;
    }

    if (entry.endsWith('.md')) {
      files.push(toPosixPath(relative(baseDirectory, fullPath)));
    }
  }

  return files;
}

function getArticleFileInfo(file) {
  const parts = toPosixPath(file).split('/');

  if (parts.length === 1) {
    return {
      articleId: file.replace(/\.md$/, ''),
      filename: file,
    };
  }

  return {
    articleId: parts[0],
    filename: parts.slice(1).join('/'),
  };
}

function getPageOrder(filename) {
  if (/^(index|main)\.md$/i.test(filename)) {
    return 0;
  }

  const numericPrefix = /^(\d+)/.exec(filename)?.[1];
  return numericPrefix ? Number(numericPrefix) : Number.MAX_SAFE_INTEGER;
}

function writePostMetadata(files) {
  const groups = new Map();

  for (const file of files) {
    const info = getArticleFileInfo(file);
    const current = groups.get(info.articleId) ?? [];

    current.push({ ...info, file });
    groups.set(info.articleId, current);
  }

  const postMetadata = Array.from(groups.entries())
    .map(([articleId, articleFiles]) => {
      const [mainFile] = [...articleFiles].sort((a, b) => (
        getPageOrder(a.filename) - getPageOrder(b.filename) || a.filename.localeCompare(b.filename)
      ));
      const content = readFileSync(resolve(POSTS_DIR, mainFile.file), 'utf-8');

      return parseFrontmatter(content, articleId);
    })
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  const outDir = dirname(POST_METADATA_FILE);
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const output = [
    '// Generated by scripts/prerender-tikz.mjs. Do not edit by hand.',
    `export const postMetadata = ${JSON.stringify(postMetadata, null, 2)} as const;`,
    '',
  ].join('\n');

  writeFileSync(POST_METADATA_FILE, output, 'utf-8');
}

// Extract all ```tikz code blocks from a markdown string
function extractTikzBlocks(markdown) {
  const regex = /```tikz\s*\n([\s\S]*?)```/g;
  const blocks = [];
  let match;
  while ((match = regex.exec(markdown)) !== null) {
    blocks.push(match[1].trim());
  }
  return blocks;
}

// Create a stable hash for a TikZ code string
function hashContent(content) {
  return createHash('sha256').update(content).digest('hex').slice(0, 16);
}

async function main() {
  console.log('🎨 Pre-rendering TikZ diagrams...\n');

  // Collect all TikZ blocks from all posts
  const files = readMarkdownFiles(POSTS_DIR);
  writePostMetadata(files);

  const allBlocks = [];
  for (const file of files) {
    const content = readFileSync(resolve(POSTS_DIR, file), 'utf-8');
    const blocks = extractTikzBlocks(content);
    if (blocks.length > 0) {
      console.log(`  📄 ${file}: found ${blocks.length} TikZ block(s)`);
      allBlocks.push(...blocks);
    }
  }

  // Also check the inline sample post
  const postsTs = resolve(ROOT, 'src/data/posts.ts');
  if (existsSync(postsTs)) {
    const postsContent = readFileSync(postsTs, 'utf-8');
    // For escaped template literals, unescape them first
    const unescaped = postsContent.replace(/\\`\\`\\`tikz/g, '```tikz').replace(/\\`\\`\\`/g, '```')
      .replace(/\\\\/g, '\\');
    const inlineBlocks = extractTikzBlocks(unescaped);
    if (inlineBlocks.length > 0) {
      console.log(`  📄 posts.ts: found ${inlineBlocks.length} TikZ block(s)`);
      allBlocks.push(...inlineBlocks);
    }
  }

  if (allBlocks.length === 0) {
    console.log('  No TikZ blocks found. Nothing to do.');
    return;
  }

  // Deduplicate by content hash
  const uniqueBlocks = new Map();
  for (const block of allBlocks) {
    const hash = hashContent(block);
    if (!uniqueBlocks.has(hash)) {
      uniqueBlocks.set(hash, block);
    }
  }

  console.log(`\n  🔧 Compiling ${uniqueBlocks.size} unique diagram(s)...\n`);

  // Check for existing cache to skip already-rendered diagrams
  let existingCache = {};
  if (existsSync(OUTPUT_FILE)) {
    try {
      existingCache = JSON.parse(readFileSync(OUTPUT_FILE, 'utf-8'));
    } catch {
      // Corrupted cache, start fresh
    }
  }

  const cache = {};
  let compiled = 0;
  let skipped = 0;

  for (const [hash, tikzCode] of uniqueBlocks) {
    // Skip if already cached
    if (existingCache[hash]) {
      cache[hash] = existingCache[hash];
      skipped++;
      console.log(`  ⏩ [${hash}] already cached, skipping`);
      continue;
    }

    try {
      // node-tikzjax needs full document structure
      const fullSource = `\\begin{document}\n${tikzCode}\n\\end{document}`;
      const svg = await tex2svg(fullSource, {
        embedFontCss: true,
      });
      cache[hash] = svg;
      compiled++;
      console.log(`  ✅ [${hash}] compiled successfully`);
    } catch (err) {
      console.error(`  ❌ [${hash}] failed: ${err.message}`);
      cache[hash] = null; // Mark as failed so we don't retry endlessly
    }
  }

  // Write the manifest
  const outDir = dirname(OUTPUT_FILE);
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  writeFileSync(OUTPUT_FILE, JSON.stringify(cache, null, 2), 'utf-8');

  console.log(`\n🎉 Done! ${compiled} compiled, ${skipped} cached. Output: ${OUTPUT_FILE}\n`);
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
